.changeset/blue-shrimps-itch.md
apps/my-vehicles/.gitignore
apps/my-vehicles/mocks/data/backend-data.ts
apps/my-vehicles/mocks/handlers/backend-handlers.ts
apps/my-vehicles/mocks/handlers/index.ts
apps/my-vehicles/mocks/index.ts
apps/my-vehicles/mocks/msw-server.ts
apps/my-vehicles/mocks/msw-worker.ts
apps/my-vehicles/next.config.mjs
apps/my-vehicles/package.json
apps/my-vehicles/src/app/api/auth/mocks/mocks-util.ts
apps/my-vehicles/src/app/api/auth/mocks/oidc/.well-known/openid-configuration/route.ts
apps/my-vehicles/src/app/api/auth/mocks/oidc/authorize/route.ts
apps/my-vehicles/src/app/api/auth/mocks/oidc/jwks/route.ts
apps/my-vehicles/src/app/api/auth/mocks/oidc/route.ts
apps/my-vehicles/src/app/api/auth/mocks/oidc/token/route.ts
apps/my-vehicles/src/app/api/auth/mocks/oidc/userinfo/route.ts
apps/my-vehicles/src/auth.ts
apps/my-vehicles/src/config/index.ts
apps/my-vehicles/src/pages/_app.tsx
apps/my-vehicles/src/pages/index.tsx
yarn.lock

Add MSW (Mock Service Worker) for APIs mock.
Add OIDC (fims) mock APIs.
**Note:**
In order to test mocks, set following env params in your local `.env.local` environment:
- **Development/Test OIDC mock** _(complete set of mock apis for OpenID Connect auth flow has been made)_: 
- `OIDC_ISSUER_URL=http://localhost:3000/api/auth/mocks/oidc`
- `OIDC_MOCK_JWT_PRIVATE_KEY="RSA private key"`
- `OIDC_MOCK_JWT_PUBLIC_KEY="RSA public key"`
- **BFF api mock**: 
- `NEXT_PUBLIC_IS_MSW_ENABLED=true`
- `NEXT_PUBLIC_BACKEND_API_MOCKING=true`
```
How to generate RSA keys:
openssl genpkey -algorithm RSA -out private.key -pkeyopt rsa_keygen_bits:2048
openssl rsa -pubout -in private.key -out public.key
```
```
MSW initialization (copy the worker script into the given directory):
cd /apps/my-vehicles
npx msw …
```

[IOPAE-1346] Add MSW and OIDC mock configurations

---

.changeset/three-carrots-tease.md
apps/my-vehicles/package.json
apps/my-vehicles/src/__tests__/test.test.ts
apps/my-vehicles/src/components/__tests__/test.test.tsx
apps/my-vehicles/src/components/test-component.tsx
apps/my-vehicles/tsconfig.json
apps/my-vehicles/vitest/vitest.config.node.mjs
apps/my-vehicles/vitest/vitest.config.react.mjs
apps/my-vehicles/vitest/vitest.setup.node.ts
apps/my-vehicles/vitest/vitest.setup.react.ts
turbo.json
yarn.lock

Add `vitest` configuration for backend and frontend unit tests.
- Follow commits history for development details.
Need to have unit test environment for both backend and frontend development.
Running the following scripts locally:
*Run all unit tests:*
`yarn workspace my-vehicles test`
*Run backend for frontend unit tests:*
`yarn workspace my-vehicles test:bff`
*Run frontend unit tests:*
`yarn workspace my-vehicles test:fe`
*As above but with the addition of code coverage summary:*
`yarn workspace my-vehicles coverage`
`yarn workspace my-vehicles coverage:bff`
`yarn workspace my-vehicles coverage:fe`

[IOPAE-1347] Add Vitest configuration

---

apps/my-vehicles/mocks/browser.ts
apps/my-vehicles/mocks/index.ts
apps/my-vehicles/mocks/server.ts
apps/my-vehicles/src/pages/_app.tsx
apps/my-vehicles/src/pages/_document.tsx

This PR updates the initialisation of msw.
- Renamed msw-worker file to browser
- Renamed msw-server file to server
- Updated setup

[IOPAE-1378] Refinement of msw

---

README.md

Just a first customization of the existing `README.md`.

[IOPAE-1374] Update main README

---

.changeset/loud-rats-build.md
apps/my-vehicles/package.json
packages/ui/package.json
packages/ui/src/components/Button.tsx
packages/ui/src/index.ts
packages/ui/tsconfig.json
yarn.lock

Add first implementation of `@ipatente/ui`, a shared UI Library for the entire project.
In this package will be developed all shared UI components for **iPatente** services.
- added `ui` under `packages` folder
- added dependency into **my-vehicles** app
Need to have a shared common ui library.
Local test with **my-vehicles** app.

[IOPAE-1405] Add @ipatente/ui shared package

---

.changeset/tender-fireants-applaud.md
apps/my-vehicles/package.json
yarn.lock

This PR adds the missing axios dependency 
- updated `package.json`

[IOPAE-1429] Added missing axios dependency 

---

.changeset/shaggy-dolls-search.md
apps/my-vehicles/package.json
turbo.json

This PR updates `coverage` script in the `package.json`
- updated `package.json`

[IOPAE-1430] Updated `coverage` script in the `package.json`

---

.changeset/calm-bananas-kneel.md
packages/ui/eslint.config.js
packages/ui/lib/components/Button.tsx
packages/ui/package.json
yarn.lock

This PR adds `eslint` and `prettier`
- updated `package.json`

[IOPAE-1414] Added `eslint` and `prettier` to `@io-ipatente/ui`

---

.changeset/forty-jeans-grow.md
apps/my-vehicles/vitest/vitest.setup.node.ts
apps/my-vehicles/vitest/vitest.setup.react.ts
packages/ui/.prettierignore
packages/ui/lib/components/__tests__/Button.test.tsx
packages/ui/package.json
packages/ui/vitest.config.js
packages/ui/vitest.setup.js
yarn.lock

Added `vitest` with coverage v8.
- added vitest setup
- added coverage v8
- added unit test on _UIButton_ sample component
Need to have test environment.
Local `dev` mode.

[IOPAE-1432] Added vitest with coverage v8

---

.changeset/strange-garlics-dress.md
packages/ui/lib/components/index.ts
packages/ui/lib/components/section-title/SectionTitle.tsx
packages/ui/lib/components/section-title/__tests__/SectionTitle.test.tsx
packages/ui/lib/components/section-title/__tests__/__snapshots__/SectionTitle.test.tsx.snap
packages/ui/lib/components/section-title/index.ts
packages/ui/lib/theme.ts
packages/ui/stories/SectionTitle.stories.tsx

This PR adds SectionTitle component to @io-ipatente/ui package
- added SectionTitle ui component
- added SectionTitle story
- added SectionTitle unit tests

[IOPAE-1409] Add SectionTitle component to @io-ipatente/ui package

---

.changeset/healthy-tables-kiss.md
packages/ui/lib/components/index.ts
packages/ui/lib/components/operation-result/OperationResult.tsx
packages/ui/lib/components/operation-result/__tests__/OperationResult.test.tsx
packages/ui/lib/components/operation-result/__tests__/__snapshots__/OperationResult.test.tsx.snap
packages/ui/lib/components/operation-result/index.ts
packages/ui/stories/OperationResult.stories.tsx

Added OperationResult component to @io-ipatente/ui package.
- added `OperationResult` ui component
- added `OperationResult` story
- added `OperationResult` unit tests
Local `dev` mode.

[IOPAE-1437] Added OperationResult component to @io-ipatente/ui package

---

.changeset/eighty-items-repair.md
apps/my-vehicles/next.config.mjs
apps/my-vehicles/src/pages/_app.tsx
packages/ui/.storybook/preview.ts
packages/ui/lib/theme.ts
packages/ui/package.json
packages/ui/vite.config.ts
yarn.lock

This PR updates the dependencies in order to improve the bundle size.
- changed dependencies to peerDependencies
- renamed theme

[IOPAE-1450] Update dependencies in @io-ipatente/ui package

---

.changeset/loud-rats-build.md

Fix wrong changeset md file.
- rename wrong `@ipatente/ui` to correct `@io-ipatente/ui` package name

bug: fix wrong changeset md file

---

.changeset/green-brooms-thank.md
apps/my-vehicles/package.json
packages/ui/package.json

Add PagoPA author on **apps** and **packages** `package.json`

chore: Add author on apps and packages package.json

---

.changeset/thin-apricots-hide.md
apps/vehicles/src/lib/bff/__tests__/wrappers.test.ts
apps/vehicles/src/lib/bff/constants.ts
apps/vehicles/src/lib/bff/errors.ts
apps/vehicles/src/lib/bff/wrappers.ts
apps/vehicles/types/next-auth.d.ts

Added withJWTAuthHandler backend for frontend wrapper, useful to manage user session (jwt) in a centralized way.
- added **withJWTAuthHandler** wrapper
- added related **unit tests**
- added some utils such as **errors** and **constants**
- formatted **next-auth.d.ts** file content
Need to manage user session in a centralized way.
Unit tests.

[IOPAE-1422] Added withJWTAuthHandler wrapper

---

.changeset/cold-ladybugs-act.md
apps/vehicles/src/app/api/infoVeicoli/route.ts
apps/vehicles/src/lib/bff/__tests__/wrappers.test.ts
apps/vehicles/src/lib/bff/business.ts
apps/vehicles/src/lib/bff/wrappers.ts
apps/vehicles/src/middleware.ts
apps/vehicles/types/next-auth.d.ts

Added GET **_infoVeicoli_** API handler.
- Added GET _**infoVeicoli**_ API handler
- Fixed next-auth JWT type augmentation
- Fixed _**withJWTAuthHandler**_ get session
- minor updates
Local `dev` mode

[IOPAE-1423] Added GET infoVeicoli api handler

---

.changeset/many-jokes-lay.md
apps/vehicles/src/components/vehicles/ListItemVehicle.tsx
apps/vehicles/src/pages/vehicles/[licensePlate].tsx
apps/vehicles/src/pages/vehicles/index.tsx
packages/ui/lib/components/list-item-action/ListItemAction.tsx
packages/ui/lib/components/list-item-action/__tests__/ListItemAction.test.tsx
packages/ui/lib/components/list-item-action/__tests__/__snapshots__/ListItemAction.test.tsx.snap
packages/ui/lib/theme.ts
packages/ui/stories/ListItemAction.stories.tsx

This PR introduces a refinement to ListItemAction component to handle loading state.
This is a first iteration.
- Refinement ListItemAction
- Updated vehicle list in order to display loading status
| vehicles  |
| - |
| <img src="https://github.com/user-attachments/assets/2e402e17-4e01-4b13-82d6-93f6fc9002d5" width="300"/> |

[IOPAE-1471] Refinement of ListItemAction

---

.changeset/lemon-eyes-sip.md
apps/vehicles/package.json
packages/core/.gitignore
packages/core/.prettierignore
packages/core/README.md
packages/core/eslint.config.mjs
packages/core/lib/bff/__tests__/client-assertion.test.ts
packages/core/lib/bff/client-assertion.ts
packages/core/lib/bff/index.ts
packages/core/lib/index.ts
packages/core/package.json
packages/core/tsconfig.json
packages/core/tsconfig.node.json
packages/core/vite.config.ts
packages/core/vitest.config.js
turbo.json
yarn.lock

Added new **@io-ipatente/core** package with generateClientAssertion function.
The goal of this core package is to enclose all the crucial and shared functionality of the various apps in the repo.
- new `@io-ipatente/core` package
- added `generateClientAssertion` functionality
- added client-assertion _unit tests_
How to use inside **apps**:
```
import { generateClientAssertion } from "@io-ipatente/core";
...
const clientAssertion = generateClientAssertion({
alg: "RS256",
aud: getConfiguration().INTEROP_CLIENT_ASSERTION_AUD,
exp: 600,
iss: getConfiguration().INTEROP_CLIENT_ASSERTION_ISS,
kid: getConfiguration().INTEROP_CLIENT_ASSERTION_KID,
privateKey: getConfiguration().INTEROP_CLIENT_ASSERTION_PK,
purposeId: getConfiguration().INTEROP_CLIENT_ASSERTION_PURPOSE_ID,
sub: …
```

[IOPAE-1424] Added @io-ipatente/core package with client assertion function

---

.changeset/wild-turtles-mix.md
apps/vehicles/src/components/vehicle-details/VehicleSectionInspections.tsx
apps/vehicles/src/components/vehicle-details/VehicleSectionRca.tsx
apps/vehicles/src/pages/vehicles/[licensePlate].tsx
packages/ui/lib/components/card-info/CardInfo.tsx
packages/ui/lib/components/card-info/__tests__/__snapshots__/CardInfo.test.tsx.snap
packages/ui/lib/theme.ts

This PR removes the license plate for each inspection.
- Removal of license plate for each inspection
- Updated ListItem padding in theme
- Updated default background colore in theme
- Updated chip size to small
Need to remove the license plate from each inspection
Local dev mode with msw mocks

[IOPAE-1488] Removal of license plate for each inspection

---

.changeset/sharp-owls-hug.md
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/pages/index.tsx
apps/vehicles/src/pages/vehicles/index.tsx
packages/ui/lib/components/empty-state/EmptyState.tsx
packages/ui/lib/components/empty-state/__tests__/EmptyState.test.tsx
packages/ui/lib/components/empty-state/__tests__/__snapshots__/EmptyState.test.tsx.snap
packages/ui/lib/components/empty-state/index.ts
packages/ui/lib/components/index.ts
packages/ui/stories/EmptyState.stories.tsx

This PR introduces the ability to display a message on-screen to a user when there are no registered vehicles.
The EmptyState component has been added to the UI library and is rendered on the `/vehicles` route
On the page containing the list of vehicles, if the user has no registered vehicles, the option to display this information on-screen is added.
The test associated with the new component in the library has been added.

[IOPAE-1403] Empty state component

---

.changeset/config.json

fix: Enable tag creation in changeset configuration

---

.changeset/calm-rats-perform.md
.changeset/soft-snakes-behave.md
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/components/vehicle-details/VehicleSectionInspections.tsx
packages/ui/lib/components/card-info/CardInfo.tsx

In the inspections section of a vehicle, an appropriate message has been added for cases where the list is empty.
In the vehicle detail view, the list of inspections is displayed, and if this list is empty, the same message shown in case of an error was previously displayed. An appropriate message has now been added
Go to the detail page of a vehicle that has no inspections, and scroll down to the inspections section

[IOPAE-1486] add RCA list empty state

---

.changeset/short-keys-marry.md
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/components/vehicle-details/VehicleSectionRca.tsx

The message displayed on the vehicle detail page has been updated for cases where there is no RCA.
Go to the detail page of a vehicle that has no RCA active, and scroll down to the RCA section.

[IPAE-1486]  update RCA empty state in vehicle detail

---

.changeset/twelve-plants-wash.md
apps/vehicles/src/utils/strings.ts

The icons associated with the various vehicle categories have been remapped.
The icons associated with the various vehicle categories were not consistent with the type of vehicle represented

[IOPAE-1483] update vehicles icons

---

.changeset/eleven-boxes-bow.md
packages/ui/lib/components/assistance-info/AssistanceInfo.tsx
packages/ui/lib/components/assistance-info/__tests__/AssistanceInfo.test.tsx
packages/ui/lib/components/assistance-info/__tests__/__snapshots__/AssistanceInfo.test.tsx.snap
packages/ui/lib/components/assistance-info/index.tsx
packages/ui/lib/components/index.ts
packages/ui/stories/AssistanceInfo.stories.tsx

A component named AssistanceInfo has been created, containing information for contacting support
On the support page, information regarding assistance must be displayed
"A test associated with the component has been added to the UI library.

[IOPAE-1491] Add AssistanceInfo card

---

packages/ui/lib/theme.ts

This PR introduces a change to the theme to resolve the error that occurred in all components using a button.
Start storybook and check that the `OperationResult` component does not fail.

chore: Fix MuiButton override in theme

---

.changeset/rude-nails-argue.md
apps/vehicles/mocks/handlers/backend-handlers.ts
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/components/shared/GenericError.tsx
apps/vehicles/src/pages/_app.tsx
apps/vehicles/src/pages/vehicles/[licensePlate].tsx
apps/vehicles/src/pages/vehicles/index.tsx
apps/vehicles/types/react-query.d.ts
packages/ui/lib/components/operation-result/OperationResult.tsx
packages/ui/lib/components/operation-result/__tests__/OperationResult.test.tsx
packages/ui/lib/components/operation-result/__tests__/__snapshots__/OperationResult.test.tsx.snap

This PR enables a generic message if an error occurs.
- updated locales
- added `GenericError` component
- updated the vehicles pages to display `GenericError` component
Need to give feedback when an error occurs
Local dev mode with msw mocks

[IOPAE-1402] Add Generic error component in vehicles

---

CODEOWNERS

Set green unit codeowner

---

.changeset/rude-comics-worry.md
apps/vehicles/.env.production

Fix env prod url

---

.changeset/early-hairs-hide.md
packages/core/lib/middleware/middleware.ts

Fix authentication flow in dev mode

---

.changeset/two-zebras-double.md
apps/vehicles/src/hooks/useVehicles.ts
apps/vehicles/src/pages/vehicles/[licensePlate].tsx

This PR is intended to wrap the select function in `useCallback` to avoid useless rerendering.

[IOPAE-1549] Wrap select function in `useCallback`

---

.changeset/orange-bananas-grow.md
packages/core/lib/wrappers/__tests__/with-jwt-auth-handler.test.ts
packages/core/lib/wrappers/__tests__/with-jwt-auth-voucher-handler.test.ts

Update request and context types in vehicles' tests
We needed to remove explicit any types

[IOPAE-1550] - fix vehicles test types

---

.changeset/poor-pens-double.md
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/components/vehicle-details/VehicleSectionRca.tsx
apps/vehicles/src/pages/assistance/index.tsx
apps/vehicles/src/pages/vehicles/index.tsx
packages/ui/lib/components/list-item-action/ListItemAction.tsx
packages/ui/lib/components/list-item-action/__tests__/__snapshots__/ListItemAction.test.tsx.snap

This PR updates the copy in several sections of the app

[IOPAE-1558] Copy review

---

.changeset/shy-lies-doubt.md
apps/vehicles/mocks/data/backend-data.ts
apps/vehicles/openapi/bff-openapi.yaml
apps/vehicles/openapi/ext-openapi.yaml
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/components/vehicle-details/VehicleSectionDetails.tsx
apps/vehicles/src/utils/strings.ts

This PR adds the `EXTRAM_MSG_006` code for the `extraMassa` field

[IOPAE-1559] Add `EXTRAM_MSG_006` code

---

.changeset/new-crews-shave.md
apps/licences/next.config.mjs
apps/licences/package.json
apps/licences/src/instrumentation.node.ts
apps/licences/src/instrumentation.ts
apps/vehicles/mocks/index.ts
apps/vehicles/mocks/server.ts
apps/vehicles/next.config.mjs
apps/vehicles/package.json
apps/vehicles/src/app/api/infoVeicoli/route.ts
apps/vehicles/src/instrumentation.node.ts
apps/vehicles/src/instrumentation.ts
yarn.lock

Bring back ApplicationInsight SDK

---

.changeset/strong-islands-switch.md
apps/licences/public/locales/en/common.json
apps/licences/public/locales/it/common.json
apps/licences/src/pages/licences/index.tsx

Updated the page header in licenses page

[IO-PAE-1553] - removed AppLayout description

---

.changeset/quick-cougars-dress.md
apps/licences/src/pages/licences/[licenseNumber].tsx
apps/vehicles/src/pages/vehicles/[licensePlate].tsx
apps/vehicles/src/pages/vehicles/index.tsx
packages/ui/lib/components/card-info/CardInfo.tsx
packages/ui/lib/components/list-item-action/ListItemAction.tsx
packages/ui/lib/components/list-item-action/__tests__/__snapshots__/ListItemAction.test.tsx.snap
packages/ui/lib/components/section-title/SectionTitle.tsx
packages/ui/lib/components/section-title/__tests__/SectionTitle.test.tsx
packages/ui/lib/components/section-title/__tests__/__snapshots__/SectionTitle.test.tsx.snap
packages/ui/stories/SectionTitle.stories.tsx

This PR introduces loading state in the detail of a vehicle and license.
- added loading state to SectionTitle component
- updated loading state to ListItemAction component
- updated label and value in CardInfo component to accept ReactNode or string

[IOPAE-1562] Add loading state in LicenceDetails and VehicleDetails

---

.changeset/thin-beans-smell.md
apps/licences/src/components/licence-details/LicenceMovementDetail.tsx

[IOPAE-1566] fix key in map inside dialog

---

.changeset/moody-lizards-cry.md
apps/licences/mocks/data/backend-data.ts

Updated licence mov mock with negative points.
- updated backend-data mock
Need to test licence negative movement points.
Local `dev` mode with `msw` mocks.

chore: Updated licence mov mock with negative points

---

.changeset/brown-boxes-type.md
apps/licences/public/locales/en/common.json
apps/licences/public/locales/it/common.json
apps/licences/src/components/licence-details/LicenceMovementDetail.tsx
apps/licences/src/pages/assistance/index.tsx
apps/licences/src/pages/licences/[licenseNumber].tsx
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json

chore: copy review

---

.changeset/neat-cats-develop.md
apps/vehicles/src/app/api/infoVeicoli/internal/route.ts

Deploy vehicles root appGateway

---

.changeset/ten-fireants-accept.md
apps/licences/public/locales/en/common.json
apps/licences/public/locales/it/common.json
apps/licences/src/components/licence-details/LicenceMovementDetail.tsx
apps/licences/src/components/licence-details/LicenceSectionDetails.tsx
apps/licences/src/components/licences/ListItemLicence.tsx
apps/licences/src/utils/constants.ts
apps/payments/src/components/payment-details/PaymentSectionDetails.tsx
apps/vehicles/src/components/vehicle-details/VehicleSectionRca.tsx
apps/vehicles/src/components/vehicles/ListItemVehicle.tsx
packages/core/lib/utils/dates.ts
packages/core/lib/utils/index.ts

This PR makes the badge licence points available in the licenses page
Modified the licences page in order to display the badge licence points for each licence
<details open><summary>Details</summary>
<p>
| licences  |
| - |
| <img src="https://github.com/user-attachments/assets/b17a9061-77b7-43d6-975a-0cbd90e0cb5a" width="300"/> |
</p>
</details>

[IOPAE-1597] show badge licence points in the licenses page

---

.changeset/weak-badgers-leave.md
apps/licences/mocks/index.ts

Disable msw warn unhandled

---

.changeset/real-clocks-bathe.md
apps/vehicles/src/components/vehicle-details/VehicleSectionDetails.tsx

[IOPAE-1615]: static detail icon in vehicles detail

---

.changeset/moody-terms-sin.md
apps/licences/openapi/ext-openapi.yaml
apps/vehicles/openapi/ext-openapi.yaml

- Add codiceFiscale required in vehicles apis
- Add codiceFiscale required in licences apis

[IOPAE-1618]: add codiceFiscale required in openapis header

---

.changeset/empty-planes-sparkle.md
apps/licences/src/middleware.ts
apps/payments/src/middleware.ts
apps/practices/src/middleware.ts
apps/vehicles/openapi/ext-openapi.yaml
apps/vehicles/src/middleware.ts
packages/core/lib/api/auth-callback-handlers.ts
packages/core/lib/auth/auth-config.ts
packages/core/lib/config/config.ts
packages/core/lib/index.ts
packages/core/lib/middleware/middleware.ts
packages/core/lib/types/index.ts
packages/core/lib/types/types.ts
packages/core/lib/utils/constants.ts
packages/core/lib/wrappers/with-jwt-auth-handler.ts
packages/core/lib/wrappers/with-jwt-auth-voucher-handler.ts

This PR updates the middleware to enhance user authentication handling, introducing support for development mode (DEV_MODE). The middleware now manages different behaviors depending on whether development mode is enabled or disabled.
- When development mode is enabled:
If the session expires, the middleware automatically refreshes the session by reinitiating the FIMS exchange
- When development mode is disabled: 
Upon session expiration, a session expired screen is displayed

[IOPAE-1632] Middleware refinement

---

.changeset/lemon-keys-wink.md
packages/core/lib/auth/auth-config.ts

This PR updates the NextAuth configuration to set a custom session expiration time. Specifically, the session will now expire after 2 hours of inactivity.

[IOPAE-1603] Set NextAuth maxAge

---

.changeset/wild-carrots-develop.md
apps/vehicles/openapi/ext-openapi.yaml

Updated external openapi nullable fields.

chore: vehicles - updated external openapi nullable fields

---

.changeset/clean-foxes-hang.md
packages/core/lib/api/auth-callback-handlers.ts
packages/core/lib/auth/auth-config.ts

Added explicit redirect uri on auth-config.

chore: Added some auth logs

---

.changeset/lucky-flies-tap.md
packages/core/lib/api/__tests__/auth-callback-handlers.test.ts
packages/core/lib/api/auth-callback-handlers.ts

Test force set callbackurl

---

.changeset/fast-clouds-repeat.md
packages/core/lib/api/auth-callback-handlers.ts

Force url with search param

---

.changeset/thin-singers-rescue.md
packages/core/lib/api/auth-callback-handlers.ts

Auth callback redirect updates

---

.changeset/eighty-mugs-run.md
packages/core/lib/api/auth-callback-handlers.ts

Fix cookie selection

---

.changeset/swift-pens-raise.md
packages/core/lib/api/__tests__/auth-callback-handlers.test.ts
packages/core/lib/api/auth-callback-handlers.ts
packages/core/lib/auth/auth-config.ts

Set cookie domain in auth callback

---

.changeset/weak-goats-own.md
packages/core/lib/api/auth-callback-handlers.ts
packages/core/lib/middleware/middleware.ts

Build CallbackUrl using Proxy Headers

---

.changeset/tender-cougars-join.md
packages/core/lib/api/__tests__/auth-callback-handlers.test.ts
packages/core/lib/api/auth-callback-handlers.ts

Test set cookie secure

---

.changeset/warm-seahorses-bathe.md
apps/licences/src/hooks/useLicences.ts
apps/licences/src/pages/_app.tsx
apps/licences/src/pages/licences/[licenseNumber].tsx
apps/licences/src/pages/licences/index.tsx
apps/vehicles/src/components/vehicle-details/VehicleSectionInspections.tsx
apps/vehicles/src/components/vehicle-details/VehicleSectionRca.tsx
packages/core/lib/api/auth-callback-handlers.ts
packages/core/lib/auth/auth-config.ts

Minor fixes

---

.changeset/stale-hotels-fry.md
apps/payments/openapi/bff-openapi.yaml
apps/payments/openapi/ext-openapi.yaml

Payments: added nullable fields on openapi specs.

chore: Payments: added nullable fields on openapi specs

---

.changeset/dry-ears-punch.md
apps/licences/src/pages/licences/[licenseNumber].tsx
packages/ui/lib/components/table/Table.tsx
packages/ui/lib/components/table/__tests__/__snapshots__/Table.test.tsx.snap

Small layout fixes in licences

[FIX]  licences layout

---

.changeset/eighty-items-divide.md
apps/licences/src/pages/licences/[licenseNumber].tsx
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/components/vehicle-details/VehicleSectionDetails.tsx

chore: Added minor fixes on vehicles and licences

---

.changeset/quick-tables-develop.md
apps/payments/src/pages/consent/index.tsx
apps/practices/src/pages/consent/index.tsx

fix: redirects

---

.changeset/curly-birds-invite.md
apps/licences/package.json
apps/payments/package.json
apps/practices/package.json
apps/vehicles/package.json

add missing .next-server-app-it folder

---

.changeset/late-shrimps-thank.md
apps/licences/src/app/api/info/route.ts
apps/licences/src/app/api/puntiPatente/route.ts
apps/payments/src/app/api/info/route.ts
apps/payments/src/app/api/pagamenti/internal/route.ts
apps/payments/src/app/api/pagamenti/route.ts
apps/practices/src/app/api/info/route.ts
apps/practices/src/app/api/pratiche/internal/route.ts
apps/practices/src/app/api/pratiche/route.ts
apps/vehicles/src/app/api/info/route.ts
apps/vehicles/src/app/api/infoVeicoli/internal/route.ts
apps/vehicles/src/app/api/infoVeicoli/route.ts

Disable cache on GET route handlers by setting dynamic=force-dynamic

---

.changeset/bright-plants-sleep.md
packages/core/lib/middleware/middleware.ts

Fix: middleware

---

.changeset/plenty-weeks-agree.md
apps/vehicles/package.json
yarn.lock

Added `@azure-rest/batch` to **io-ipatente-vehicles** webapp.

chore: Added @azure-rest/batch to io-ipatente-vehicles

---

.changeset/wicked-mirrors-drive.md
apps/licences/package.json
apps/payments/package.json
apps/practices/package.json
apps/vehicles/package.json
yarn.lock

Update Unidici Instrumentation OTEL 0.3.0 -> 0.7.1

---

.changeset/lovely-ravens-burn.md
apps/licences/package.json
apps/payments/package.json
apps/practices/package.json
apps/vehicles/package.json
yarn.lock

Pin down applicationinsight

---

.changeset/calm-cheetahs-sort.md
apps/licences/next.config.mjs
apps/payments/next.config.mjs
apps/practices/next.config.mjs
apps/vehicles/next.config.mjs

chore: disable source map in prod

---

.changeset/thirty-bugs-glow.md
apps/licences/src/app/api/puntiPatente/internal/route.ts
apps/payments/src/app/api/pagamenti/internal/route.ts
apps/practices/src/app/api/pratiche/internal/route.ts
apps/vehicles/src/app/api/infoVeicoli/internal/route.ts

add internal route for licences

fix : Internal licences route

---

.changeset/many-buses-deny.md
README.md

First major release 1.0.0 for each app:
- io-ipatente-licences
- io-ipatente-payments
- io-ipatente-practices
- io-ipatente-vehicles

First major release for each app

---

.changeset/clever-crabs-shake.md
apps/vehicles/public/locales/en/common.json
apps/vehicles/public/locales/it/common.json
apps/vehicles/src/components/vehicle-details/VehicleSectionRca.tsx

chore: removed rca expiration info

---

.changeset/chilled-rockets-sin.md
apps/licences/src/app/api/voucher/internal/route.ts

[IOPAE-1904] add internal get voucher route

---

.changeset/mean-lamps-dance.md

Bump next to `14.2.15`

---

.changeset/dirty-sloths-accept.md
apps/licences/src/app/api/puntiPatenteWithoutVoucher/internal/route.ts

add new api puntiPatenteWithoutVoucher for testing

[IOPAE-1931]add new api puntiPatenteWithoutVoucher

---

.changeset/rude-jeans-remember.md
apps/licences/package.json
apps/payments/package.json
apps/practices/package.json
apps/vehicles/package.json
yarn.lock

Bump:
- vite from 5.4.10 to 5.4.15
- vitest from 2.1.3 to 2.1.9
- axios from 1.7.7 to 1.8.4

[IOPAE-1939] Bump vite, vitest, axios

---

.changeset/itchy-pens-hope.md
apps/licences/src/app/api/puntiPatente/route.ts

add logs in case of axios error

---

.changeset/silent-rules-fetch.md
apps/licences/src/app/api/puntiPatente/internal/route.ts
apps/licences/src/app/api/puntiPatente/route.ts

fix: use same log for internal and prod

---

.changeset/hip-cows-mate.md
apps/licences/src/app/api/puntiPatente/internal/route.ts
apps/licences/src/app/api/puntiPatente/route.ts

fix : update logs

---

.changeset/twelve-mayflies-juggle.md
apps/licences/package.json
yarn.lock

Update applicationinsights to 3.6.0 for licences webapp.

chore: Licences: Update applicationinsights to 3.6.0

---

.changeset/sour-dryers-double.md
apps/payments/package.json
apps/practices/package.json
apps/vehicles/package.json
yarn.lock

fix : update applicationinsight

---

.changeset/moody-countries-fetch.md
apps/licences/src/pages/consent/index.tsx
packages/core/lib/middleware/middleware.ts

Updated redirectPath definition on middleware and usage on consent page.

[IOPAE-2000] Updated redirectPath definition on middleware and usage on consent page

---

.changeset/silver-poems-jam.md
apps/licences/src/pages/consent/index.tsx
packages/core/lib/middleware/middleware.ts

Added redirectPath cookie on consent page redirection.

[IOPAE-2000] Added redirectPath cookie on consent page redirection

---

apps/licences/.opex/licences/env/prod/config.yaml
apps/vehicles/.opex/vehicles/env/prod/config.yaml

[IOPAE-2026] use domain-specific offcall action group to opex dashboard

---

.changeset/empty-tables-fix.md
apps/licences/src/components/licences/ListItemLicence.tsx

Removed licence _status badge_ on `ListItemLicence`.
Local `dev` mode with `msw` mock.
The following images show the layout of the `ListItemLicence` before and after removing the status badge:
<p>
</p>

[IOPAE-2082] Removed licence status badge on ListItemLicence
